[package]
name = "rust_query_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
serde_yaml = "0.9.16"
regex = "1.7.0"
struct_iterable = "0.1.1"
